### ISSUE TITLE
Forward Policy - require package

### ISSUE THREAD

**Issue by Kriechi** [attachmentgenie/attachmentgenie-ufw#43]
https://github.com/attachmentgenie/attachmentgenie-ufw/blob/master/manifests/init.pp#L48-53
Should this require `Package['ufw']`?

Otherwise I get an error on the first run:
```
Error: /Stage[main]/Ufw/File_line[forward policy]: Could not evaluate: No such file or directory @ rb_sysopen - /etc/default/ufw
```

**Comment by igalic** [comment]
:+1:
