### ISSUE TITLE
does the code working for Ubuntu 14 + Puppet 4?

### ISSUE THREAD

**Issue by lkthomas** [attachmentgenie/attachmentgenie-ufw#52]
does the code working for Ubuntu 14 + Puppet 4? why does it state "build failing" ?

**Comment by igalic** [comment]
i'm using it on 14.04 with puppet 4.latest
i don't know about 16.04 tho

**Comment by attachmentgenie** [comment]
I am currently working on implementing testkitchen/beaker tests because this seems to be happening a lot of late

**Comment by attachmentgenie** [comment]
after closing #51, the answer to your questions is yes.  the following test matrix works for me.

master ~/Devshed/Projects/attachmentgenie-ufw> bundle exec kitchen list                                                                               
Instance             Driver   Provisioner  Verifier  Transport  Last Action
puppet3-ubuntu-1204  Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet3-ubuntu-1404  Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet3-debian-711   Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet3-debian-85    Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet4-ubuntu-1404  Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet4-ubuntu-1604  Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet4-debian-711   Vagrant  PuppetApply  Inspec    Ssh        Verified
puppet4-debian-85    Vagrant  PuppetApply  Inspec    Ssh        Verified

**Comment by attachmentgenie** [comment]
it states failing as some of the tests are currently failing due to some refactoring
